routes/web.php
<?php
use Intervention\Image\ImageManagerStatic as Image;
use App\models\Restaurant;
use App\models\Staff;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

Route::get('/dd',function (){
    $img = Image::make(public_path('/uploads/dd.jpg'))->resize(1200, 900)->insert(public_path('/uploads/q1.png'),'top-right',50,50);
    // $img = Image::make(public_path('/uploads/dd.jpg'))->resize(400, null);
    return $img->response('jpg');
});
Route::get('/login', 'Auth\LoginController@loginForm');
Route::get('/','ClientController@home')->name('home');
Route::get('/staff/all','ClientController@allstaff');
Route::get('/staff/profile/{id}','ClientController@profilestaff');
Route::get('/job/all','ClientController@alljob');
Route::post('/cv/upload','admin\ApplicantController@cvupload');
Route::post('/contact/us','admin\UserController@contactus');
Route::get('/setlocale/{locale}',function($locale){

    Session::put('locale',$locale);

return redirect()->back();
});
Auth::routes();
Route::group( [ 'prefix' => 'admin',  'middleware' => ['auth','administrator'] , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::post('fee/delete','UserController@deleteFee');
    Route::post('/update_fee','UserController@updateFee');
    Route::get('/services','ServiceController@index')->name('services.index');
    Route::get('/aboutus/show','UserController@showRequests');
    Route::get('/services/create','ServiceController@create');
    Route::post('/services/store','ServiceController@store')->name('services.store');;
    Route::get('/services/edit/{id}','ServiceController@edit');
    Route::post('/services/update','ServiceController@update')->name('services.update');
    Route::post('/services/destroy','ServiceController@destroy');

    Route::get('/team','TeamController@index')->name('team.index');;
    Route::get('/team/create','TeamController@create');
    Route::post('/team/store','TeamController@store')->name('team.store');;
    Route::get('/team/edit/{id}','TeamController@edit');
    Route::post('/team/update','TeamController@update')->name('teams.update');
    Route::post('/team/destroy','TeamController@destroy');

    Route::get('/jobApplications','JobApplicationController@index')->name('JobApplications.index');
    Route::get('/jobApplications/create','JobApplicationController@create');
    Route::post('/jobApplications/store','JobApplicationController@store')->name('JobApplications.store');
    Route::get('/jobApplications/edit/{id}','JobApplicationController@edit');
    Route::post('/aboutus/update','AboutusController@update')->name('aboutus.update');
    Route::get('/aboutus/edit/{id}','AboutusController@edit');

Route::get('/jobApplications/applicant/{id}','ApplicantController@aplicantbyjob');
    Route::post('/jobApplications/update','JobApplicationController@update')->name('JobApplications.update');
    Route::post('/jobApplications/destroy','JobApplicationController@destroy');

    Route::get('/staff','StaffController@index')->name('staff.index');
    Route::get('/staff/create','StaffController@create');
    Route::post('/staff/store','StaffController@store')->name('staff.store');
    Route::get('/staff/edit/{id}','StaffController@edit');
    Route::post('/staff/update/{id}','StaffController@update')->name('staff.update');
    Route::post('/staff/destroy','StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/show/{id}','StaffController@show');


    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('/restaurants', 'RestaurantController@index')->name('restaurants');
    Route::get('/restaurants/create', 'RestaurantController@create')->name('restaurants.create');
    Route::post('/restaurants/store', 'RestaurantController@store')->name('restaurants.store');
    Route::resource('/categories', 'CategoryController');
    Route::get('/category/search', 'CategoryController@search')->name('categories.search');
    Route::get('/delivery/list', 'DeliveryController@index')->name('delivery.index');
Route::get('/delivery/edit/{id}','DeliveryController@edit')->name('delivery.edit');
Route::post('/delivery/update/{id}','DeliveryController@update')->name('delivery.update');
    Route::resource('/orders', 'OrderController');
    Route::post('/order/status','OrderController@changeStatus')->name('orders.status');
    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/products', 'ProductController');
    Route::get('/products/variation/{id}/edit', 'ProductController@editVariation')->name('products.variation.edit');
    Route::put('/products/variation/{id}/update', 'ProductController@updateVariation')->name('products.variation.update');
    Route::get('/product/search', 'ProductController@search')->name('products.search');
    Route::resource('/cities', 'CityController');
    Route::resource('/inquiries', 'InquiryController');
    Route::get('/inquiries/user/{id}', 'InquiryController@userInquiries')->name('userInquires');
    Route::get('/start_chat/{id}', 'InquiryController@start_chat');
    Route::resource('/productTypes', 'ProductTypeController');
    Route::resource('/attributes', 'AttributeController');
    Route::post('/attribute/save', 'AttributeController@save')->name('attributes.save');
    Route::get('/attribute/trans/{id}', 'AttributeController@attribute_trans')->name('attributes.trans');
    Route::post('/attribute/translate', 'AttributeController@attribute_trans_values')->name('attributes.value_trans');
    Route::resource('/ads', 'AdsController');
    Route::resource('/complaints', 'ComplaintController');
    Route::post('/complaint/status', 'ComplaintController@changeStatus')->name('complaints.status');
    Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
    Route::get('/users/logs/index', 'UserController@log_index')->name('logs.index');
    Route::get('/users/{id}/logs', 'UserController@user_log')->name('users.logs.show');
    Route::get('/notifications','NotificationController@getNew')->name('notifications.new');
    Route::resource('/alerts','AlertController');
    Route::post('/alert/send','AlertController@send')->name('alerts.send');
    Route::get('/reports/sales','ReportController@salesReport')->name('reports.sales');
    Route::post('/reports/custom','ReportController@salesReport');
    Route::get('/reports/items','ReportController@itemsReport')->name('reports.items');
    Route::resource('/regions', 'RegionsController');
    Route::get('/city/{id}/regions', 'CityController@GetCityRegions');
    Route::get('/address/{id}','AddressController@GetUsersAddress')->name('users.address');
    Route::get('/restaurants/edit/{id}','RestaurantController@edit')->name('restaurants.edit');
    Route::post('/restaurants/update','RestaurantController@update')->name('restaurants.update');
    Route::get('/products/edit/{id}','ProductController@edit');
    Route::post('/products/update/{id}','ProductController@update');
    Route::post('/products/delete','ProductController@destroy');
    Route::post('/products/addfoodtypes','ProductController@add_foodtypes');
    Route::get('/appinfo','AppinfoController@index')->name('appinfo.index');
    Route::post('/appinfo/update','AppinfoController@update')->name('appinfo.update');
    Route::get('/foodtypes','FoodTypeController@index');
    Route::post('/foodtypes/destroy/{id}','FoodTypeController@destroy');
    Route::get('/categories/delete/{id}','CategoryController@destroy');
    Route::post('/address/store','AddressController@store');
    Route::get('/pennding/orders','OrderController@penndingorders');
    Route::post('/order/edit/{id}','OrderController@updateorder')->name('orderupdate');

    Route::get('/notifications/count','NotificationController@count');
    Route::get('/users_count/count','UserController@count');
    Route::post('/product_delete/delete','ProductController@destroy');
    Route::get('/qucickaccess','AppinfoController@quickaccess');
    Route::post('/spiner/winner','UserController@spinerwinner');
    Route::post('/spiner','UserController@spiner');
    Route::post('/update_password','UserController@update_password');

    Route::post('/foodtype/proiority','FoodTypeController@changepriority');

    Route::get('/notifications/clear','NotificationController@clear');
    Route::post('/notifications/change_isnew','NotificationController@change_isnew');
    Route::post('/add_fee','UserController@addFee');
    Route::post('/update_fee','UserController@updateFee');


});

Route::get('/privacy-policy',function (){return view('privacy-policy');});
Route::get('/test',function (){    return view('admin.reports.salesReport');});

Route::get('/resize',function (){
    $restaurnats=Restaurant::get();
       foreach($restaurnats as $restaurnat){
               $info=pathinfo($restaurnat->image_url);
               $sub=$info['basename'];
           $img=Image::make(public_path('uploads/restaurants/'.$sub));
           if($img->height() > 200){
               $img = $img->resize(null, 200);
           }
           if($img->width() > 200){
               $img = $img->resize(200, null);
           }
           $hash = time().md5($img->__toString());
           $target = public_path('uploads/restaurants/'.$hash.'.'.$info['extension']);
           $img->save($target);
           $restaurnat->tmp_image=url('/uploads/restaurants/'.$hash.'.'.$info['extension']);
           $restaurnat->save();
           // end thumbnail
       }
       return response()->json("Yes");
    });

app/models/Ads.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Ads extends Model
{
    protected $table = 'ads';
    protected $guarded = ["id","image","created_at","updated_at"];
    protected $hidden = ["image_path"];

    public function get_item()
    {
            return false;
    }

    // public function region()
    // {
    //     return $this->belongsTo('App\Models\Region');
    // }
}

app/Http/Controllers/admin/AdsController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Ads;
use App\models\Product;
use App\models\Region;
use App\models\City;
use App\models\UserActivity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rule;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Support\Facades\Auth;
class AdsController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.ads.index';
        $this->create_view = 'admin.ads.create';
        $this->show_view = 'admin.ads.show';
        $this->edit_view = 'admin.ads.edit';
        $this->index_route = 'admin.ads.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Ads::class;
    }

    private function StoreValidationRules($request)
    {
        return [
            'image' => 'required',
        ];
    }

    private function UpdateValidationRules($request)
    {
        return [
            'image' => 'required',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $ads = $this->model_instance::all();
        return view($this->index_view, compact('ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        has_access('ads_create');
        return view($this->create_view);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        has_access('ads_create'); 
        $validated_data = $request->validate($this->StoreValidationRules($request));
        try {
            $object = $this->model_instance::create($validated_data);
            if($request->hasFile('image'))
            {
                $image = $validated_data['image'];
                $img = Image::make($image->getRealPath())->encode('jpg');
                    $img = $img->resize(1200, 900);
                $hash = time().md5($img->__toString());
                $target = public_path('uploads/ads/'.$hash.'.jpg');
                $img->save($target);

                $object->image_url = url('/uploads/ads/'.$hash.'.jpg');
                $object->image_path = 'ads/'.$hash.'.jpg';
                $object->update();
            } 

            $log_message = trans('ads.create_log') . '#' . $object->id;
            UserActivity::logActivity($log_message);
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {

            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $category = $this->model_instance::findOrFail($id);
        return view($this->show_view, compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        has_access('ads_update');
        $ads = $this->model_instance::findOrFail($id);
        return view($this->edit_view, compact('ads'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        has_access('ads_update');
        $validated_data = $request->validate($this->UpdateValidationRules($request));
        try {
            $object = $this->model_instance::find($id);
            $updated_instance = $object->update($validated_data);
            if($request->hasFile('image'))
            {
                hl_deleteFile($object->image_path);
                $image = $validated_data['image'];
                $img = Image::make($image->getRealPath())->encode('jpg');
                    $img = $img->resize(1200, 900);
                $hash = time().md5($img->__toString());
                $target = public_path('uploads/ads/'.$hash.'.jpg');
                $img->save($target);

                $object->image_url = url('/uploads/ads/'.$hash.'.jpg');
                $object->image_path = 'ads/'.$hash.'.jpg';
                $object->update();
            }
            $log_message = trans('ads.update_log') . '#' . $object->id;
            UserActivity::logActivity($log_message);
            if ($updated_instance) {
                return redirect()->route($this->index_route)->with('success', $this->update_success_message);
            } else {
                return redirect()->route($this->index_route)->with('error', $this->update_error_message);
            }
        } catch (\Exception $ex) {
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {


        has_access('ads_remover');

        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                $log_message = trans('ads.delete_log') . '#' . $id;
                UserActivity::logActivity($log_message);
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }
        }

        return redirect()->route($this->index_route);
    }
}

app/Http/Controllers/api/AdsController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Resources\Category as CategoryResource;
use App\Http\Resources\Product as ProductResource;
use App\models\Ads;
use App\models\User;
use App\models\Category;
use App\models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdsController extends Controller
{ 

    public function index($id)
    {
        $user=User::where('id',$id)->first();
$ads = Ads::get(); 
$adsToReturn=[];
$ad_type="";
foreach($ads as $ad){
$ad['foodtype_id']=null;
    if($ad["type"] == "product"){
        $ad["ad_type"]="product"; 
        $ad['foodtype_id']=Product::where('id',$ad["item_id"])->first()->food_type_id;
    }
    else if($ad["type"] == "category"){
        $ad["ad_type"]="category";
    }
    else{
        $ad["ad_type"]="";
    } 
    if(in_array($user->city_id,json_decode($ad->city_id,true))){
        array_push($adsToReturn,$ad);
    }
    
}
        return response()->json($adsToReturn);
    }
}

resources/views/admin/ads/create.blade.php
@extends('layouts.app')

@section('title','ADs')

@section('styles')

    <style>
        .wrapper-pic {
            position: relative;
            display: inline-block;
            opacity: 1;
        }

        .wrapper-pic:hover {
            transition: all .2s ease-in-out;
        }

        .wrapper-pic:hover .edit {
            transition: all .2s ease-in-out;
            display: block;
        }

        .edit {
            padding-top: 7px;
            padding-right: 7px;
            position: absolute;
            left: 20px;
            top: 10px;
            display: none;
        }
    </style>

@endsection


@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-custom">
                    <div class="card-header">
                     <div class="card-title">

                      <h3 class="card-label">
                        Create Ad
                                    </h3>
                     </div>
                           <div class="card-toolbar">
                               <a href="#" onclick="sub();" class="btn btn-sm btn-primary font-weight-bold">
                                   @lang('admin.create')
                               </a>
                           </div>
                    </div>
                    <div class="card-body">
                        <form id="create" method="POST" action="{{ route('admin.ads.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">

                            <div class="col-sm-12 wrapper-pic">
                                    <img src="" class="img-fluid" id="category_image" style=" height: 300px; ">
                                <div class="edit">
                                    <a onclick="event.preventDefault();openChangeImage()" class="btn btn-success btn-xs">@lang('admin.edit')</a>
                                    <a  class="btn btn-danger btn-xs" onclick="event.preventDefault();removeImage()">@lang('admin.delete')</a>
                                </div>
                                <input type="file" id="category_image_id" onchange="previewImage(event)" name="image" style="display:none" accept="image/*">
                                <input type="hidden" name="image_flag" id="image_flag" >

                        </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script>
        $("#region_select").select2();
function sub()
{
    $('#create').submit();
}
        function enableCategorySearching() {
            var searchUrl = '{{ route('admin.categories.search') }}';
            searchingFor(searchUrl);
            attachCategory();


        }

        function attachCategory(){
            $('#ads_item').off('select2:select').on('select2:select', function (event) {
                var id = $(event.currentTarget).find("option:selected").val();
                if(confirm('@lang('admin.sure_to_add_category')'))
                {
                    $('#selected_item').attr('value',id);
                }
            });
        }

        function attachProduct(){
            $('#ads_item').off('select2:select').on('select2:select', function (event) {
                var id = $(event.currentTarget).find("option:selected").val();
                if(confirm('@lang('admin.sure_to_add_product')'))
                {
                    $('#selected_item').attr('value',id);
                }
            });
        }

        function enableProductSearching() {
            var searchUrl = '{{ route('admin.products.search') }}';
            searchingFor(searchUrl);
            attachProduct();
        }


        function searchingFor(url)
        {
            //console.log(url);
            if(url === '')
            {
                return;
            }
            $('#ads_item').empty();
            $('#ads_item').select2({
                placeholder: "اكتب اسم الوجبة",
                minimumInputLength: 2,
                ajax: {
                    url: url,
                    dataType: 'json',
                    data: function (params) {
                        return {
                            q: $.trim(params.term),
                            d:true
                        };
                    },
                    processResults: function (data) {
                      //  console.log(data);
                        return {
                            results: data
                        };
                    },
                    error: function (err) {
                        console.log(err);
                    },
                    cache: true
                }
            });
        }






       function get_item_data(event)
        {
            var selected_value  = $(event.target).val();
            if(selected_value === "product"){
                $("#adForId").css("display", "flex");
                enableProductSearching();}
            // else if(selected_value === "category")
            //     enableCategorySearching();
            else if(selected_value === "ads")
            {
                $("#adForId").css("display", "none");
                $('#ads_item').empty();
                var ele = `<option value="ads">اعلان مجرد</option>`;
                $('#ads_item').append(ele);
            }
            else if(selected_value === "offers")
            {
                $('#ads_item').empty();
                var ele = `<option value="offers">اعلان لصفحة العروض</option>`;
                $('#ads_item').append(ele);
            }
        }

        enableProductSearching();


    </script>
    <script>
        function openChangeImage()
        {
            $("#category_image_id").trigger('click');
        }

        function removeImage() {
            var default_image_url = "https://tsdist.com/wp-content/uploads/2018/07/Image_placeholder_1.jpg";
            $('#category_image').attr('src',default_image_url);
            $('#category_image_id').val('');
            change_image_flag('remove')
        }
        removeImage();
        function change_image_flag(flag) {
            $("#image_flag").attr('value',flag);
        }


        function previewImage(event) {
            var image_src =  URL.createObjectURL(event.target.files[0]);
            $('#category_image').attr('src',image_src);
            change_image_flag('edit')

        }
    </script>
@endsection

resources/views/admin/ads/index.blade.php
@extends('layouts.app')

@section('title','Ads')

@section('content')

@if(session('success'))
    <div class="alert alert-custom alert-outline-2x alert-outline-primary fade show mb-5" role="alert">
        <div class="alert-icon"><i class="flaticon-warning"></i></div>
        <div class="alert-text">{{session('success')}}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif
<div class="d-flex flex-column-fluid">

    <div class="container">
     <div class="row" style="margin: auto">
         <a href="{{ route('admin.ads.create') }}" class="btn btn-primary" ><i class="fa fa-plus"></i> @lang('admin.add_new')</a>
     </div>
        <div class="row">
            @foreach($ads as $ad)
         <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
             <!--begin::Card-->
             <div class="card card-custom gutter-b card-stretch">
                 <!--begin::Body-->


                 <div class="card-header" >
                <lable class="text-md-right" style="margin-top: 25px;">
                        {{ $ad->title ?? '' }}</lable>
                     <div class="card-toolbar">
                         <a href="{{ route('admin.ads.edit',$ad->id) }}" class="btn btn-icon btn-xs btn-light-primary mr-1" data-card-tool="edit">
                             <i class="fa fa-edit"></i>
                         </a>

                         <a href="#" onclick="deleteItem_new('{{ $ad->id }}','{{route('admin.ads.destroy',$ad->id)}}')" class="btn btn-icon btn-xs btn-light-danger" data-card-tool="remove">
                             <i class="fa fa-trash"></i>
                         </a>
                     </div>
                 </div>
                 <a href="{{ route('admin.ads.edit',$ad->id) }}">
                 <div class="card-body pt-4">

                     <!--begin::User-->
                     <div class="d-flex align-items-end mb-7">
                         <!--begin::Pic-->
                         <div class="d-flex align-items-center">
                             <!--begin::Pic-->
                             <div class="flex-shrink-0 mr-4 mt-lg-0 mt-3">
                                 <div class="symbol symbol-circle symbol-lg-150">
                                     <img src="{{$ad->image_url}}" alt="image">
                                 </div>
                             </div>
                             <!--end::Pic-->
                             <!--begin::Title-->

                             <!--end::Title-->
                         </div>


                         <!--end::Title-->
                     </div>
                     <!--end::User-->
                     <!--begin::Desc-->
                     <p class="mb-7">
                        <div class="d-flex flex-column">
                            <div class="text-dark font-weight-bold text-hover-primary font-size-h4 mb-0">
                                {{ $ad->get_item()->name ?? trans('ads.'.$ad->type) }}
                            </div>
                            <span class="text-muted font-weight-bold">{{ trans('ads.'.$ad->type) }}</span>
                        </div>



                     </p>
                     <!--end::Desc-->

                 </div>
                 </a>
                 <!--end::Body-->
             </div>
             <!--end::Card-->
         </div>
         @endforeach
        </div>
    </div>
 </div>

@endsection


@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json"
                }
            });

        });
        function deleteItem_new(id,url) {

            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'JSON',
                data: {_token: '{!! csrf_token() !!}', _method : 'delete' },
                success: function (response) {
                    location.reload();
                    },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log(textStatus, errorThrown);

                    }
            })

    }

    </script>

@endsection

resources/views/admin/ads/show.blade.php
@extends('layouts.app')

@section('title','')

@section('content')

    <h1>show page</h1>

@endsection