routes/web.php
<?php
use Intervention\Image\ImageManagerStatic as Image;
use App\models\Restaurant;
use App\models\Staff;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

Route::get('/dd',function (){
    $img = Image::make(public_path('/uploads/dd.jpg'))->resize(1200, 900)->insert(public_path('/uploads/q1.png'),'top-right',50,50);
    // $img = Image::make(public_path('/uploads/dd.jpg'))->resize(400, null);
    return $img->response('jpg');
});
Route::get('/login', 'Auth\LoginController@loginForm');
Route::get('/','ClientController@home')->name('home');
Route::get('/staff/all','ClientController@allstaff');
Route::get('/staff/profile/{id}','ClientController@profilestaff');
Route::get('/job/all','ClientController@alljob');
Route::post('/cv/upload','admin\ApplicantController@cvupload');
Route::post('/contact/us','admin\UserController@contactus');
Route::get('/setlocale/{locale}',function($locale){

    Session::put('locale',$locale);

return redirect()->back();
});
Auth::routes();
Route::group( [ 'prefix' => 'admin',  'middleware' => ['auth','administrator'] , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::post('fee/delete','UserController@deleteFee');
    Route::post('/update_fee','UserController@updateFee');
    Route::get('/services','ServiceController@index')->name('services.index');
    Route::get('/aboutus/show','UserController@showRequests');
    Route::get('/services/create','ServiceController@create');
    Route::post('/services/store','ServiceController@store')->name('services.store');;
    Route::get('/services/edit/{id}','ServiceController@edit');
    Route::post('/services/update','ServiceController@update')->name('services.update');
    Route::post('/services/destroy','ServiceController@destroy');

    Route::get('/team','TeamController@index')->name('team.index');;
    Route::get('/team/create','TeamController@create');
    Route::post('/team/store','TeamController@store')->name('team.store');;
    Route::get('/team/edit/{id}','TeamController@edit');
    Route::post('/team/update','TeamController@update')->name('teams.update');
    Route::post('/team/destroy','TeamController@destroy');

    Route::get('/jobApplications','JobApplicationController@index')->name('JobApplications.index');
    Route::get('/jobApplications/create','JobApplicationController@create');
    Route::post('/jobApplications/store','JobApplicationController@store')->name('JobApplications.store');
    Route::get('/jobApplications/edit/{id}','JobApplicationController@edit');
    Route::post('/aboutus/update','AboutusController@update')->name('aboutus.update');
    Route::get('/aboutus/edit/{id}','AboutusController@edit');

Route::get('/jobApplications/applicant/{id}','ApplicantController@aplicantbyjob');
    Route::post('/jobApplications/update','JobApplicationController@update')->name('JobApplications.update');
    Route::post('/jobApplications/destroy','JobApplicationController@destroy');

    Route::get('/staff','StaffController@index')->name('staff.index');
    Route::get('/staff/create','StaffController@create');
    Route::post('/staff/store','StaffController@store')->name('staff.store');
    Route::get('/staff/edit/{id}','StaffController@edit');
    Route::post('/staff/update/{id}','StaffController@update')->name('staff.update');
    Route::post('/staff/destroy','StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/show/{id}','StaffController@show');


    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('/restaurants', 'RestaurantController@index')->name('restaurants');
    Route::get('/restaurants/create', 'RestaurantController@create')->name('restaurants.create');
    Route::post('/restaurants/store', 'RestaurantController@store')->name('restaurants.store');
    Route::resource('/categories', 'CategoryController');
    Route::get('/category/search', 'CategoryController@search')->name('categories.search');
    Route::get('/delivery/list', 'DeliveryController@index')->name('delivery.index');
Route::get('/delivery/edit/{id}','DeliveryController@edit')->name('delivery.edit');
Route::post('/delivery/update/{id}','DeliveryController@update')->name('delivery.update');
    Route::resource('/orders', 'OrderController');
    Route::post('/order/status','OrderController@changeStatus')->name('orders.status');
    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/products', 'ProductController');
    Route::get('/products/variation/{id}/edit', 'ProductController@editVariation')->name('products.variation.edit');
    Route::put('/products/variation/{id}/update', 'ProductController@updateVariation')->name('products.variation.update');
    Route::get('/product/search', 'ProductController@search')->name('products.search');
    Route::resource('/cities', 'CityController');
    Route::resource('/inquiries', 'InquiryController');
    Route::get('/inquiries/user/{id}', 'InquiryController@userInquiries')->name('userInquires');
    Route::get('/start_chat/{id}', 'InquiryController@start_chat');
    Route::resource('/productTypes', 'ProductTypeController');
    Route::resource('/attributes', 'AttributeController');
    Route::post('/attribute/save', 'AttributeController@save')->name('attributes.save');
    Route::get('/attribute/trans/{id}', 'AttributeController@attribute_trans')->name('attributes.trans');
    Route::post('/attribute/translate', 'AttributeController@attribute_trans_values')->name('attributes.value_trans');
    Route::resource('/ads', 'AdsController');
    Route::resource('/complaints', 'ComplaintController');
    Route::post('/complaint/status', 'ComplaintController@changeStatus')->name('complaints.status');
    Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
    Route::get('/users/logs/index', 'UserController@log_index')->name('logs.index');
    Route::get('/users/{id}/logs', 'UserController@user_log')->name('users.logs.show');
    Route::get('/notifications','NotificationController@getNew')->name('notifications.new');
    Route::resource('/alerts','AlertController');
    Route::post('/alert/send','AlertController@send')->name('alerts.send');
    Route::get('/reports/sales','ReportController@salesReport')->name('reports.sales');
    Route::post('/reports/custom','ReportController@salesReport');
    Route::get('/reports/items','ReportController@itemsReport')->name('reports.items');
    Route::resource('/regions', 'RegionsController');
    Route::get('/city/{id}/regions', 'CityController@GetCityRegions');
    Route::get('/address/{id}','AddressController@GetUsersAddress')->name('users.address');
    Route::get('/restaurants/edit/{id}','RestaurantController@edit')->name('restaurants.edit');
    Route::post('/restaurants/update','RestaurantController@update')->name('restaurants.update');
    Route::get('/products/edit/{id}','ProductController@edit');
    Route::post('/products/update/{id}','ProductController@update');
    Route::post('/products/delete','ProductController@destroy');
    Route::post('/products/addfoodtypes','ProductController@add_foodtypes');
    Route::get('/appinfo','AppinfoController@index')->name('appinfo.index');
    Route::post('/appinfo/update','AppinfoController@update')->name('appinfo.update');
    Route::get('/foodtypes','FoodTypeController@index');
    Route::post('/foodtypes/destroy/{id}','FoodTypeController@destroy');
    Route::get('/categories/delete/{id}','CategoryController@destroy');
    Route::post('/address/store','AddressController@store');
    Route::get('/pennding/orders','OrderController@penndingorders');
    Route::post('/order/edit/{id}','OrderController@updateorder')->name('orderupdate');

    Route::get('/notifications/count','NotificationController@count');
    Route::get('/users_count/count','UserController@count');
    Route::post('/product_delete/delete','ProductController@destroy');
    Route::get('/qucickaccess','AppinfoController@quickaccess');
    Route::post('/spiner/winner','UserController@spinerwinner');
    Route::post('/spiner','UserController@spiner');
    Route::post('/update_password','UserController@update_password');

    Route::post('/foodtype/proiority','FoodTypeController@changepriority');

    Route::get('/notifications/clear','NotificationController@clear');
    Route::post('/notifications/change_isnew','NotificationController@change_isnew');
    Route::post('/add_fee','UserController@addFee');
    Route::post('/update_fee','UserController@updateFee');


});

Route::get('/privacy-policy',function (){return view('privacy-policy');});
Route::get('/test',function (){    return view('admin.reports.salesReport');});

Route::get('/resize',function (){
    $restaurnats=Restaurant::get();
       foreach($restaurnats as $restaurnat){
               $info=pathinfo($restaurnat->image_url);
               $sub=$info['basename'];
           $img=Image::make(public_path('uploads/restaurants/'.$sub));
           if($img->height() > 200){
               $img = $img->resize(null, 200);
           }
           if($img->width() > 200){
               $img = $img->resize(200, null);
           }
           $hash = time().md5($img->__toString());
           $target = public_path('uploads/restaurants/'.$hash.'.'.$info['extension']);
           $img->save($target);
           $restaurnat->tmp_image=url('/uploads/restaurants/'.$hash.'.'.$info['extension']);
           $restaurnat->save();
           // end thumbnail
       }
       return response()->json("Yes");
    });

resources/views/admin/alerts/create.blade.php
@extends('layouts.app')

@section('title',trans('ads.create'))


@section('styles')

    <style>

        .wrapper-pic {
            position: relative;
            display: inline-block;
            opacity: 1;
        }

        .wrapper-pic:hover {
            transition: all .2s ease-in-out;
        }

        .wrapper-pic:hover .edit {
            transition: all .2s ease-in-out;
            display: block;
        }

        .edit {
            padding-top: 7px;
            padding-right: 7px;
            position: absolute;
            left: 20px;
            top: 10px;
            display: none;
        }


    </style>


@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-custom">
                    <div class="card-header">
                            <div class="card-title">
                                <span class="card-icon">
                                    <i class="flaticon2-notification text-primary"></i>
                                </span>
                                <h3 class="card-label">@lang('alerts.create')
                            </h3>
                            </div>
                            <div class="card-toolbar">
                                <a href="#" onclick="$('#create_form').submit();" class="btn btn-sm btn-success font-weight-bold">
                                <i class="flaticon2-cube"></i>@lang('admin.add_new')</a>
                            </div>

                    </div>

                    <div class="card-body">
                        <form id="create_form" method="POST" action="{{ route('admin.alerts.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-8">


                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right" data-required="yes">@lang('alerts.title')</label>

                                <div class="col-md-10">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" required autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.type')</label>

                                <div class="col-md-10">
                                    <select name="type" id="select_type" class="form-control select2" onchange="display_productsay(event)">
                                        <option value="public" selected>إشعار عام</option>
                                        <option value="product">إشعار لمنتج</option>

                                    </select>
                                </div>
                            </div>

                            <div class="form-group row" id="products" style="display: none">
                                <label class="col-md-2 col-form-label text-md-right" data-required="yes">@lang('ads.item')</label>

                                <div class="col-lg-10 col-md-9 col-sm-12">
                                    <select class="form-control select2" id="kt_select2_1" name="product_id">
                                        @foreach ($products as $product )
                                        <option value="{{ $product->id }}">{{ $product->name }} - {{$product->restaurant->user->username}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right" data-required="yes">@lang('alerts.message')</label>

                                <div class="col-md-10">
                                    <textarea name="message" required autofocus class="form-control form-control-lg form-control-solid" cols="30" rows="5"></textarea>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.image')</label>

                                <div class="col-md-10">

                                    <div class="image-input image-input-empty image-input-outline" id="kt_image_4" style="background-image: url(assets/media/users/blank.png)">
                                        <div class="image-input-wrapper"></div>

                                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                         <i class="fa fa-pen icon-sm text-muted"></i>
                                         <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                                         <input type="hidden" name="profile_avatar_remove"/>
                                        </label>

                                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                                         <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>

                                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                                         <i class="ki ki-bold-close icon-xs text-muted"></i>
                                        </span>
                                       </div>
                                </div>
                            </div>




                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('scripts')

    <script>
        $('#select_type').select2({ width: '100%',});
        $('#kt_select2_1').select2({
            width: '100%',
           });
           $('#kt_select2_1').data('select2').$selection.css('height', '34px');
           $('#select_type').data('select2').$selection.css('height', '34px');
       function display_productsay(event)
        {
            var x=document.getElementById("products");
            var selected_value  = $(event.target).val();
            if(selected_value === "product"){
                x.style.display="flex";

            }
            else  x.style.display="none";

        }




    </script>
@endsection

resources/views/admin/alerts/index.blade.php
@extends('layouts.app')
@section('title',trans('alerts.alerts'))

@section('content')

<div class="container-fluid">
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Entry-->
        <div class="d-flexf flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-header flex-wrap border-0 pt-6 pb-0">
                        <div class="card-title">
                            <h3 class="card-label">@lang('alerts.alerts')
                        </div>
                        <div class="card-toolbar">
                            <!--begin::Button-->
                            <a href="/admin/alerts/create" class="btn btn-primary font-weight-bolder"  >
                            <span class="svg-icon svg-icon-md">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <circle fill="#000000" cx="9" cy="15" r="6" />
                                        <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span>@lang('alerts.create')</a>
                            <!--end::Button-->
                        </div>
                    </div>
                    <div class="card-body">

                        <!--begin: Datatable-->
                        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('alerts.title')</th>
                                    <th>@lang('alerts.message')</th>
                                    <th>نوع الاشعار</th>
                                    <th>@lang('admin.settings')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($app_alerts as $alert)
                                <tr>

                                    <td>{{ $alert->id }}</td>
                                    <td>{{ $alert->title ?? '' }}</td>
                                    <td>{{ $alert->message ?? '' }}</td>

                                <td> {{ $alert->product_id?   'إشعار لمنتج' :'إشعار عام' }}
                                    <span class="d-block text-muted pt-2 font-size-sm">{{ $alert->product->name ?? '' }}
                                    </span>
                                </td>
                                    <td>
                                        <span style="overflow: visible; position: relative; width: 125px;">
                                            <div class="dropdown dropdown-inline">

                                            <a href="#"  onclick="event.preventDefault();sendAlert('{{ $alert->id }}','{{ route('admin.alerts.send') }}')" class="btn btn-sm btn-light btn-text-primary btn-icon mr-2" title="Send notification">
                                                <span class="svg-icon svg-icon-md svg-icon-primary"><!--begin::Svg Icon | path:C:\wamp64\www\keenthemes\themes\metronic\theme\html\demo1\dist/../src/media/svg/icons\Communication\Send.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"/>
                                                        <path d="M3,13.5 L19,12 L3,10.5 L3,3.7732928 C3,3.70255344 3.01501031,3.63261921 3.04403925,3.56811047 C3.15735832,3.3162903 3.45336217,3.20401298 3.70518234,3.31733205 L21.9867539,11.5440392 C22.098181,11.5941815 22.1873901,11.6833905 22.2375323,11.7948177 C22.3508514,12.0466378 22.2385741,12.3426417 21.9867539,12.4559608 L3.70518234,20.6826679 C3.64067359,20.7116969 3.57073936,20.7267072 3.5,20.7267072 C3.22385763,20.7267072 3,20.5028496 3,20.2267072 L3,13.5 Z" fill="#000000"/>
                                                    </g>
                                                </svg><!--end::Svg Icon--></span>
                                            </a>
                                            <a href="#"  onclick="deleteItem('{{ $alert->id }}','{{ route('admin.alerts.destroy',$alert->id) }}')" class="btn btn-sm btn-light btn-text-primary btn-icon" title="Delete">
                                               <span class="svg-icon svg-icon-md svg-icon-primary">
                                                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                     <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"></path>
                                                        <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"></path>
                                                     </g>
                                                  </svg>
                                               </span>
                                            </a>
                                         </span>
                                    </td>

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
</div>


@endsection


@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json"
                }
            });

        });



        function deleteItem(id,url) {




                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                    ,
                    success: function (response) {
                    location.reload();
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                    console.log(textStatus, errorThrown);

                    }
                });
        }



        function sendAlert(id,url) {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', alert_id : id }
                })
                    .done(function() {

                    alert("{!! trans('admin.sent_successfully') !!}");
                        swal({title: "{!! trans('admin.done') !!}", text: "{!! trans('admin.sent_successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {
                        console.log(e)
                    })
        }

    </script>

@endsection